# Generated by Django 5.2.2 on 2025-06-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='image_url',
        ),
    ]
